// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/log-meal.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.88.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated. Connect your MacNutrition account first." }],
    isError: true
  };
}
function fail(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function ok(text, structuredContent) {
  return { content: [{ type: "text", text }], ...structuredContent ? { structuredContent } : {} };
}
function dayBounds(date) {
  const d = date && /^\d{4}-\d{2}-\d{2}$/.test(date) ? date : (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
  return [`${d}T00:00:00.000Z`, `${d}T23:59:59.999Z`, d];
}

// src/lib/mcp/tools/log-meal.ts
var log_meal_default = defineTool({
  name: "log_meal",
  title: "Log a meal",
  description: "Log a meal with its macros for the signed-in MacNutrition user.",
  inputSchema: {
    name: z.string().trim().min(1).describe("Meal name, e.g. 'Chicken and rice'."),
    calories: z.number().min(0).max(1e4).describe("Calories (kcal)."),
    protein: z.number().min(0).max(1e3).describe("Protein in grams."),
    carbs: z.number().min(0).max(1e3).describe("Carbohydrates in grams."),
    fats: z.number().min(0).max(1e3).describe("Fat in grams."),
    sugar: z.number().min(0).max(1e3).optional().describe("Sugar in grams."),
    notes: z.string().max(500).optional().describe("Optional notes about the meal."),
    logged_at: z.string().optional().describe("ISO timestamp for when the meal was eaten. Defaults to now.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("meals").insert({
      user_id: ctx.getUserId(),
      name: input.name,
      calories: input.calories,
      protein: input.protein,
      carbs: input.carbs,
      fats: input.fats,
      sugar: input.sugar ?? 0,
      notes: input.notes ?? null,
      ...input.logged_at ? { logged_at: input.logged_at } : {}
    }).select().single();
    if (error) return fail(error.message);
    const [, , day] = dayBounds(String(data.logged_at).slice(0, 10));
    return ok(
      `Logged "${data.name}" (${data.calories} kcal, ${data.protein}g protein, ${data.carbs}g carbs, ${data.fats}g fat) on ${day}.`,
      { meal: data }
    );
  }
});

// src/lib/mcp/tools/list-meals.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_meals_default = defineTool2({
  name: "list_meals",
  title: "List meals for a day",
  description: "List the signed-in user's logged meals for a given day (defaults to today).",
  inputSchema: {
    date: z2.string().optional().describe("Day in YYYY-MM-DD format. Defaults to today.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const [start, end, day] = dayBounds(date);
    const { data, error } = await supabaseForUser(ctx).from("meals").select("id, name, calories, protein, carbs, fats, sugar, notes, logged_at").gte("logged_at", start).lte("logged_at", end).order("logged_at", { ascending: true });
    if (error) return fail(error.message);
    const meals = data ?? [];
    if (meals.length === 0) return ok(`No meals logged on ${day}.`, { date: day, meals: [] });
    const lines = meals.map(
      (m) => `- ${m.name}: ${m.calories} kcal, P ${m.protein}g / C ${m.carbs}g / F ${m.fats}g`
    );
    return ok(`Meals on ${day}:
${lines.join("\n")}`, { date: day, meals });
  }
});

// src/lib/mcp/tools/log-water.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var log_water_default = defineTool3({
  name: "log_water",
  title: "Log water intake",
  description: "Log water intake in millilitres for the signed-in MacNutrition user.",
  inputSchema: {
    amount_ml: z3.number().min(1).max(5e3).describe("Amount of water in millilitres."),
    logged_at: z3.string().optional().describe("ISO timestamp. Defaults to now.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ amount_ml, logged_at }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("water_intake").insert({ user_id: ctx.getUserId(), amount_ml, ...logged_at ? { logged_at } : {} }).select().single();
    if (error) return fail(error.message);
    return ok(`Logged ${amount_ml} ml of water.`, { entry: data });
  }
});

// src/lib/mcp/tools/get-daily-summary.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var get_daily_summary_default = defineTool4({
  name: "get_daily_summary",
  title: "Get daily nutrition summary",
  description: "Get the signed-in user's totals for a day (calories, macros, water) compared with their MacNutrition targets.",
  inputSchema: {
    date: z4.string().optional().describe("Day in YYYY-MM-DD format. Defaults to today.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const [start, end, day] = dayBounds(date);
    const [mealsRes, waterRes, baselineRes] = await Promise.all([
      supabase.from("meals").select("calories, protein, carbs, fats, sugar").gte("logged_at", start).lte("logged_at", end),
      supabase.from("water_intake").select("amount_ml").gte("logged_at", start).lte("logged_at", end),
      supabase.from("user_baselines").select("target_calories, protein_grams, carbs_grams, fats_grams, water_liters").maybeSingle()
    ]);
    if (mealsRes.error) return fail(mealsRes.error.message);
    if (waterRes.error) return fail(waterRes.error.message);
    const totals = (mealsRes.data ?? []).reduce(
      (acc, m) => ({
        calories: acc.calories + (m.calories ?? 0),
        protein: acc.protein + (m.protein ?? 0),
        carbs: acc.carbs + (m.carbs ?? 0),
        fats: acc.fats + (m.fats ?? 0),
        sugar: acc.sugar + (m.sugar ?? 0)
      }),
      { calories: 0, protein: 0, carbs: 0, fats: 0, sugar: 0 }
    );
    const waterMl = (waterRes.data ?? []).reduce((sum, w) => sum + (w.amount_ml ?? 0), 0);
    const targets = baselineRes.data ?? null;
    const summary = {
      date: day,
      totals,
      water_ml: waterMl,
      targets: targets ? {
        calories: targets.target_calories,
        protein: targets.protein_grams,
        carbs: targets.carbs_grams,
        fats: targets.fats_grams,
        water_ml: targets.water_liters ? Math.round(Number(targets.water_liters) * 1e3) : null
      } : null
    };
    const t = summary.targets;
    const text = [
      `Nutrition summary for ${day}:`,
      `Calories: ${Math.round(totals.calories)}${t?.calories ? ` / ${t.calories}` : ""} kcal`,
      `Protein: ${Math.round(totals.protein)}${t?.protein ? ` / ${t.protein}` : ""} g`,
      `Carbs: ${Math.round(totals.carbs)}${t?.carbs ? ` / ${t.carbs}` : ""} g`,
      `Fat: ${Math.round(totals.fats)}${t?.fats ? ` / ${t.fats}` : ""} g`,
      `Water: ${waterMl}${t?.water_ml ? ` / ${t.water_ml}` : ""} ml`
    ].join("\n");
    return ok(text, summary);
  }
});

// src/lib/mcp/tools/get-nutrition-targets.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_nutrition_targets_default = defineTool5({
  name: "get_nutrition_targets",
  title: "Get nutrition targets and profile",
  description: "Get the signed-in user's MacNutrition baseline: daily calorie and macro targets, hydration target, goal, diet type and allergies.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("user_baselines").select(
      "primary_goal, activity_level, diet_type, allergies, conditions, target_calories, protein_grams, carbs_grams, fats_grams, sugar_grams, water_liters, unit_system"
    ).maybeSingle();
    if (error) return fail(error.message);
    if (!data) return ok("No baseline found yet. Complete onboarding in the MacNutrition app first.", { targets: null });
    const text = [
      `Goal: ${data.primary_goal ?? "not set"}`,
      `Diet: ${data.diet_type ?? "balanced"}`,
      `Calories: ${data.target_calories ?? "not set"} kcal/day`,
      `Protein: ${data.protein_grams ?? "not set"} g`,
      `Carbs: ${data.carbs_grams ?? "not set"} g`,
      `Fat: ${data.fats_grams ?? "not set"} g`,
      `Water: ${data.water_liters ?? "not set"} L/day`,
      data.allergies?.length ? `Allergies: ${data.allergies.join(", ")}` : ""
    ].filter(Boolean).join("\n");
    return ok(text, { targets: data });
  }
});

// src/lib/mcp/tools/get-progress.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^3.25.76";
var get_progress_default = defineTool6({
  name: "get_progress",
  title: "Get recent progress updates",
  description: "List the signed-in user's recent weight and progress check-ins from MacNutrition.",
  inputSchema: {
    limit: z5.number().min(1).max(50).optional().describe("How many recent updates to return. Defaults to 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("progress_updates").select("*").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return fail(error.message);
    const rows = data ?? [];
    if (rows.length === 0) return ok("No progress updates logged yet.", { updates: [] });
    const lines = rows.map((r) => {
      const date = String(r.created_at ?? "").slice(0, 10);
      const weight = r.weight_kg ?? r.weight ?? null;
      return `- ${date}${weight ? `: ${weight} kg` : ""}`;
    });
    return ok(`Recent progress updates:
${lines.join("\n")}`, { updates: rows });
  }
});

// src/lib/mcp/index.ts
var projectRef = "nfqaanowocbcnymcqcig";
var mcp_default = defineMcp({
  name: "macnutrition-mcp",
  title: "MacNutrition",
  version: "0.1.0",
  instructions: "Tools for MacNutrition, a UK-first nutrition coaching app. Use `get_nutrition_targets` for the user's daily calorie, macro and hydration targets; `log_meal` and `log_water` to record intake; `list_meals` and `get_daily_summary` to review a day; `get_progress` for recent weight check-ins. All values are metric (grams, ml, kg). Never recalculate the user's targets yourself \u2014 read them with `get_nutrition_targets`.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_nutrition_targets_default,
    get_daily_summary_default,
    list_meals_default,
    log_meal_default,
    log_water_default,
    get_progress_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
